# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iOS Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Sample

  pod 'UICollectionViewSplitLayout', :path => '../'

  target 'iOS SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
